/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TermsAndPrivacyRouteImport } from "./routes/terms-and-privacy";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as NotesRouteImport } from "./routes/notes";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NotesIndexRouteImport } from "./routes/notes.index";
import { Route as NotesNoteIdRouteImport } from "./routes/notes.$noteId";

const TermsAndPrivacyRoute = TermsAndPrivacyRouteImport.update({
    id: "/terms-and-privacy",
    path: "/terms-and-privacy",
    getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
    id: "/signup",
    path: "/signup",
    getParentRoute: () => rootRouteImport,
} as any);
const NotesRoute = NotesRouteImport.update({
    id: "/notes",
    path: "/notes",
    getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
    id: "/login",
    path: "/login",
    getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const NotesIndexRoute = NotesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => NotesRoute,
} as any);
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
    id: "/$noteId",
    path: "/$noteId",
    getParentRoute: () => NotesRoute,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/notes": typeof NotesRouteWithChildren;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes/": typeof NotesIndexRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes": typeof NotesIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/notes": typeof NotesRouteWithChildren;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes/": typeof NotesIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | "/"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/notes"
        | "/signup"
        | "/terms-and-privacy"
        | "/notes/$noteId"
        | "/notes/";
    fileRoutesByTo: FileRoutesByTo;
    to:
        | "/"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/signup"
        | "/terms-and-privacy"
        | "/notes/$noteId"
        | "/notes";
    id:
        | "__root__"
        | "/"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/notes"
        | "/signup"
        | "/terms-and-privacy"
        | "/notes/$noteId"
        | "/notes/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    DashboardRoute: typeof DashboardRoute;
    ForgotPasswordRoute: typeof ForgotPasswordRoute;
    LoginRoute: typeof LoginRoute;
    NotesRoute: typeof NotesRouteWithChildren;
    SignupRoute: typeof SignupRoute;
    TermsAndPrivacyRoute: typeof TermsAndPrivacyRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/terms-and-privacy": {
            id: "/terms-and-privacy";
            path: "/terms-and-privacy";
            fullPath: "/terms-and-privacy";
            preLoaderRoute: typeof TermsAndPrivacyRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/signup": {
            id: "/signup";
            path: "/signup";
            fullPath: "/signup";
            preLoaderRoute: typeof SignupRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/notes": {
            id: "/notes";
            path: "/notes";
            fullPath: "/notes";
            preLoaderRoute: typeof NotesRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/login": {
            id: "/login";
            path: "/login";
            fullPath: "/login";
            preLoaderRoute: typeof LoginRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/forgot-password": {
            id: "/forgot-password";
            path: "/forgot-password";
            fullPath: "/forgot-password";
            preLoaderRoute: typeof ForgotPasswordRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard": {
            id: "/dashboard";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/notes/": {
            id: "/notes/";
            path: "/";
            fullPath: "/notes/";
            preLoaderRoute: typeof NotesIndexRouteImport;
            parentRoute: typeof NotesRoute;
        };
        "/notes/$noteId": {
            id: "/notes/$noteId";
            path: "/$noteId";
            fullPath: "/notes/$noteId";
            preLoaderRoute: typeof NotesNoteIdRouteImport;
            parentRoute: typeof NotesRoute;
        };
    }
}

interface NotesRouteChildren {
    NotesNoteIdRoute: typeof NotesNoteIdRoute;
    NotesIndexRoute: typeof NotesIndexRoute;
}

const NotesRouteChildren: NotesRouteChildren = {
    NotesNoteIdRoute: NotesNoteIdRoute,
    NotesIndexRoute: NotesIndexRoute,
};

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    DashboardRoute: DashboardRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    LoginRoute: LoginRoute,
    NotesRoute: NotesRouteWithChildren,
    SignupRoute: SignupRoute,
    TermsAndPrivacyRoute: TermsAndPrivacyRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
