/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TokensRouteImport } from "./routes/tokens";
import { Route as TermsAndPrivacyRouteImport } from "./routes/terms-and-privacy";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as NotesRouteImport } from "./routes/notes";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as AiFeaturesRouteImport } from "./routes/ai-features";
import { Route as ActivityRouteImport } from "./routes/activity";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NotesIndexRouteImport } from "./routes/notes.index";
import { Route as NotesNoteIdRouteImport } from "./routes/notes.$noteId";
import { Route as AdminUsersRouteImport } from "./routes/admin.users";
import { Route as AdminTokenEconomyRouteImport } from "./routes/admin.token-economy";
import { Route as AdminSettingsRouteImport } from "./routes/admin.settings";
import { Route as AdminAnalyticsRouteImport } from "./routes/admin.analytics";
import { Route as AdminActivityLogsRouteImport } from "./routes/admin.activity-logs";

const TokensRoute = TokensRouteImport.update({
    id: "/tokens",
    path: "/tokens",
    getParentRoute: () => rootRouteImport,
} as any);
const TermsAndPrivacyRoute = TermsAndPrivacyRouteImport.update({
    id: "/terms-and-privacy",
    path: "/terms-and-privacy",
    getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
    id: "/signup",
    path: "/signup",
    getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => rootRouteImport,
} as any);
const NotesRoute = NotesRouteImport.update({
    id: "/notes",
    path: "/notes",
    getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
    id: "/login",
    path: "/login",
    getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => rootRouteImport,
} as any);
const AiFeaturesRoute = AiFeaturesRouteImport.update({
    id: "/ai-features",
    path: "/ai-features",
    getParentRoute: () => rootRouteImport,
} as any);
const ActivityRoute = ActivityRouteImport.update({
    id: "/activity",
    path: "/activity",
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const NotesIndexRoute = NotesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => NotesRoute,
} as any);
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
    id: "/$noteId",
    path: "/$noteId",
    getParentRoute: () => NotesRoute,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
    id: "/admin/users",
    path: "/admin/users",
    getParentRoute: () => rootRouteImport,
} as any);
const AdminTokenEconomyRoute = AdminTokenEconomyRouteImport.update({
    id: "/admin/token-economy",
    path: "/admin/token-economy",
    getParentRoute: () => rootRouteImport,
} as any);
const AdminSettingsRoute = AdminSettingsRouteImport.update({
    id: "/admin/settings",
    path: "/admin/settings",
    getParentRoute: () => rootRouteImport,
} as any);
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
    id: "/admin/analytics",
    path: "/admin/analytics",
    getParentRoute: () => rootRouteImport,
} as any);
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
    id: "/admin/activity-logs",
    path: "/admin/activity-logs",
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/activity": typeof ActivityRoute;
    "/ai-features": typeof AiFeaturesRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/notes": typeof NotesRouteWithChildren;
    "/settings": typeof SettingsRoute;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/tokens": typeof TokensRoute;
    "/admin/activity-logs": typeof AdminActivityLogsRoute;
    "/admin/analytics": typeof AdminAnalyticsRoute;
    "/admin/settings": typeof AdminSettingsRoute;
    "/admin/token-economy": typeof AdminTokenEconomyRoute;
    "/admin/users": typeof AdminUsersRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes/": typeof NotesIndexRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/activity": typeof ActivityRoute;
    "/ai-features": typeof AiFeaturesRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/settings": typeof SettingsRoute;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/tokens": typeof TokensRoute;
    "/admin/activity-logs": typeof AdminActivityLogsRoute;
    "/admin/analytics": typeof AdminAnalyticsRoute;
    "/admin/settings": typeof AdminSettingsRoute;
    "/admin/token-economy": typeof AdminTokenEconomyRoute;
    "/admin/users": typeof AdminUsersRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes": typeof NotesIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/activity": typeof ActivityRoute;
    "/ai-features": typeof AiFeaturesRoute;
    "/dashboard": typeof DashboardRoute;
    "/forgot-password": typeof ForgotPasswordRoute;
    "/login": typeof LoginRoute;
    "/notes": typeof NotesRouteWithChildren;
    "/settings": typeof SettingsRoute;
    "/signup": typeof SignupRoute;
    "/terms-and-privacy": typeof TermsAndPrivacyRoute;
    "/tokens": typeof TokensRoute;
    "/admin/activity-logs": typeof AdminActivityLogsRoute;
    "/admin/analytics": typeof AdminAnalyticsRoute;
    "/admin/settings": typeof AdminSettingsRoute;
    "/admin/token-economy": typeof AdminTokenEconomyRoute;
    "/admin/users": typeof AdminUsersRoute;
    "/notes/$noteId": typeof NotesNoteIdRoute;
    "/notes/": typeof NotesIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | "/"
        | "/activity"
        | "/ai-features"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/notes"
        | "/settings"
        | "/signup"
        | "/terms-and-privacy"
        | "/tokens"
        | "/admin/activity-logs"
        | "/admin/analytics"
        | "/admin/settings"
        | "/admin/token-economy"
        | "/admin/users"
        | "/notes/$noteId"
        | "/notes/";
    fileRoutesByTo: FileRoutesByTo;
    to:
        | "/"
        | "/activity"
        | "/ai-features"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/settings"
        | "/signup"
        | "/terms-and-privacy"
        | "/tokens"
        | "/admin/activity-logs"
        | "/admin/analytics"
        | "/admin/settings"
        | "/admin/token-economy"
        | "/admin/users"
        | "/notes/$noteId"
        | "/notes";
    id:
        | "__root__"
        | "/"
        | "/activity"
        | "/ai-features"
        | "/dashboard"
        | "/forgot-password"
        | "/login"
        | "/notes"
        | "/settings"
        | "/signup"
        | "/terms-and-privacy"
        | "/tokens"
        | "/admin/activity-logs"
        | "/admin/analytics"
        | "/admin/settings"
        | "/admin/token-economy"
        | "/admin/users"
        | "/notes/$noteId"
        | "/notes/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    ActivityRoute: typeof ActivityRoute;
    AiFeaturesRoute: typeof AiFeaturesRoute;
    DashboardRoute: typeof DashboardRoute;
    ForgotPasswordRoute: typeof ForgotPasswordRoute;
    LoginRoute: typeof LoginRoute;
    NotesRoute: typeof NotesRouteWithChildren;
    SettingsRoute: typeof SettingsRoute;
    SignupRoute: typeof SignupRoute;
    TermsAndPrivacyRoute: typeof TermsAndPrivacyRoute;
    TokensRoute: typeof TokensRoute;
    AdminActivityLogsRoute: typeof AdminActivityLogsRoute;
    AdminAnalyticsRoute: typeof AdminAnalyticsRoute;
    AdminSettingsRoute: typeof AdminSettingsRoute;
    AdminTokenEconomyRoute: typeof AdminTokenEconomyRoute;
    AdminUsersRoute: typeof AdminUsersRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/tokens": {
            id: "/tokens";
            path: "/tokens";
            fullPath: "/tokens";
            preLoaderRoute: typeof TokensRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/terms-and-privacy": {
            id: "/terms-and-privacy";
            path: "/terms-and-privacy";
            fullPath: "/terms-and-privacy";
            preLoaderRoute: typeof TermsAndPrivacyRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/signup": {
            id: "/signup";
            path: "/signup";
            fullPath: "/signup";
            preLoaderRoute: typeof SignupRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/settings": {
            id: "/settings";
            path: "/settings";
            fullPath: "/settings";
            preLoaderRoute: typeof SettingsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/notes": {
            id: "/notes";
            path: "/notes";
            fullPath: "/notes";
            preLoaderRoute: typeof NotesRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/login": {
            id: "/login";
            path: "/login";
            fullPath: "/login";
            preLoaderRoute: typeof LoginRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/forgot-password": {
            id: "/forgot-password";
            path: "/forgot-password";
            fullPath: "/forgot-password";
            preLoaderRoute: typeof ForgotPasswordRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard": {
            id: "/dashboard";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/ai-features": {
            id: "/ai-features";
            path: "/ai-features";
            fullPath: "/ai-features";
            preLoaderRoute: typeof AiFeaturesRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/activity": {
            id: "/activity";
            path: "/activity";
            fullPath: "/activity";
            preLoaderRoute: typeof ActivityRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/notes/": {
            id: "/notes/";
            path: "/";
            fullPath: "/notes/";
            preLoaderRoute: typeof NotesIndexRouteImport;
            parentRoute: typeof NotesRoute;
        };
        "/notes/$noteId": {
            id: "/notes/$noteId";
            path: "/$noteId";
            fullPath: "/notes/$noteId";
            preLoaderRoute: typeof NotesNoteIdRouteImport;
            parentRoute: typeof NotesRoute;
        };
        "/admin/users": {
            id: "/admin/users";
            path: "/admin/users";
            fullPath: "/admin/users";
            preLoaderRoute: typeof AdminUsersRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/admin/token-economy": {
            id: "/admin/token-economy";
            path: "/admin/token-economy";
            fullPath: "/admin/token-economy";
            preLoaderRoute: typeof AdminTokenEconomyRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/admin/settings": {
            id: "/admin/settings";
            path: "/admin/settings";
            fullPath: "/admin/settings";
            preLoaderRoute: typeof AdminSettingsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/admin/analytics": {
            id: "/admin/analytics";
            path: "/admin/analytics";
            fullPath: "/admin/analytics";
            preLoaderRoute: typeof AdminAnalyticsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/admin/activity-logs": {
            id: "/admin/activity-logs";
            path: "/admin/activity-logs";
            fullPath: "/admin/activity-logs";
            preLoaderRoute: typeof AdminActivityLogsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

interface NotesRouteChildren {
    NotesNoteIdRoute: typeof NotesNoteIdRoute;
    NotesIndexRoute: typeof NotesIndexRoute;
}

const NotesRouteChildren: NotesRouteChildren = {
    NotesNoteIdRoute: NotesNoteIdRoute,
    NotesIndexRoute: NotesIndexRoute,
};

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ActivityRoute: ActivityRoute,
    AiFeaturesRoute: AiFeaturesRoute,
    DashboardRoute: DashboardRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    LoginRoute: LoginRoute,
    NotesRoute: NotesRouteWithChildren,
    SettingsRoute: SettingsRoute,
    SignupRoute: SignupRoute,
    TermsAndPrivacyRoute: TermsAndPrivacyRoute,
    TokensRoute: TokensRoute,
    AdminActivityLogsRoute: AdminActivityLogsRoute,
    AdminAnalyticsRoute: AdminAnalyticsRoute,
    AdminSettingsRoute: AdminSettingsRoute,
    AdminTokenEconomyRoute: AdminTokenEconomyRoute,
    AdminUsersRoute: AdminUsersRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
